// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "PlayerSpaceShip":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . 9 9 . . . . . . . 
. . . . . . . 9 9 . . . . . . . 
. . . . . . 6 9 9 6 . . . . . . 
. . . . . 8 6 9 9 6 8 . . . . . 
. . . . 8 6 8 6 6 8 6 8 . . . . 
. . . . 8 6 8 8 8 8 6 8 . . . . 
. . . 8 6 6 8 6 6 8 6 6 8 . . . 
. . 6 8 8 8 8 c b 8 8 8 8 6 . . 
. 6 8 8 d d b c c b d d 8 8 6 . 
. 6 8 d b c f . . f c b d 8 6 . 
. . . f c . . . . . . c f . . . 
. . . . f . . . . . . f . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image2":
            case "Warning Icon":return img`
....................
....................
....................
......ccccccc.......
......c44444c.......
......c4fff4c.......
.....cc4fff4cc......
.....cc4fff4cc......
....cc44fff44cc.....
...ccc44fff44ccc....
...cc444fff44ccc....
..cc4444fff4444cc...
..cc44444444444cc...
..c44444fff44444c...
..c44444fff44444c...
..c4444444444444c...
..ccccccccccccccc...
....................
....................
....................
`;
            case "image3":
            case "Boss":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
